name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASS: ${{secrets.DOCKER_PASS}}
      run: 
        docker login -u $DOCKER_LOGIN -p $DOCKER_PASS
    - name: build
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: push
      run: docker push ${{secrets.DOCKER_USER}}/pollub-pwco
